#pragma once

#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 2
#define ENGINE_VERSION_PATCH 4

#define ENGINE_BUILD_NUMBER 231
#define ENGINE_BUILD_BRANCH_OFFSET 57
#define ENGINE_GIT_HASH "87a76b4"
#define ENGINE_GIT_BRANCH "dev"
#define ENGINE_BUILD_TIMESTAMP "20260223212955"
#define ENGINE_GIT_DIRTY 1
