if(EXISTS "${CMAKE_BINARY_DIR}/BuildManagement/Debug_Build_Flag.txt")
	file(REMOVE "${CMAKE_BINARY_DIR}/BuildManagement/Debug_Build_Flag.txt")
	message("Debug build was conducted, forcing release build.")
    include("${CMAKE_CURRENT_LIST_DIR}/DebugBuildActions.cmake")
elseif(EXISTS "${CMAKE_BINARY_DIR}/BuildManagement/Release_Build_Flag.txt")
	file(REMOVE "${CMAKE_BINARY_DIR}/BuildManagement/Release_Build_Flag.txt")
	message("Release build was conducted, forcing debug build.")
    include("${CMAKE_CURRENT_LIST_DIR}/ReleaseBuildActions.cmake")
endif()